language: go

env:
  global:
    - CC_TEST_REPORTER_ID=1e35bbee1876f5801b50f0f066ccbb7384c07516bdb1330a850f109caaba45dd

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./scripts/build.sh

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
