language: go

go:
  - 1.x

env:
  global:
    - CC_TEST_REPORTER_ID=1e35bbee1876f5801b50f0f066ccbb7384c07516bdb1330a850f109caaba45dd

install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

  - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release && chmod +x ./semantic-release

  - go get github.com/tcnksm/ghr

before_script:
  - ./cc-test-reporter before-build

script:
  - ./scripts/build.sh

after_script:
  - ./scripts/cc_coverage.sh

after_success:
  - ./scripts/release.sh
